"""Update user model: remove foo-bar, add email

Revision ID: 0f502dbfb259
Revises: ce025475ea73
Create Date: 2026-02-02 14:24:13.315015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f502dbfb259"
down_revision: Union[str, Sequence[str], None] = "ce025475ea73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", sa.String(length=100), nullable=False)
    )
    op.drop_constraint(op.f("uq_users_foo_bar"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "foo")
    op.drop_column("users", "bar")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("bar", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("foo", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("uq_users_foo_bar"),
        "users",
        ["foo", "bar"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "email")
    # ### end Alembic commands ###
